### ISSUE TITLE
[Sugerencia por Fumired] / Correo opcional.

### ISSUE THREAD

**Issue by gmorales254** [gmorales254/CRMLite#6]
La idea que me solicitaron es que tenga la posibilidad de obviar el correo en base a un checkbox que me lo habilite o no, debo evaluar como seria la mejor forma para revisar este asunto o simplemente dejarlo en limpio.

- [x] Verificar en la base si implica algo.
- [x] Cambios del front para que no capture el valor " " o vacío como un dato a chequear en la base.
- [x] Quitar el "requerido" del campo correo.

**Comment by gmorales254** [comment]
Quedó pronto!

**Comment by Max-Oliver** [comment]
Genial bro
