### ISSUE TITLE
Create class components to separete the logic by responsability

### ISSUE THREAD

**Issue by Max-Oliver** [gmorales254/CRMLite#7]
#### First, determine when start one logic of a feature or validation utils, and when it finish it,
then just create a new file, maybe in a class to get more readability but it's optional..

And then just import the functionality when you need to  use it.. so..

Your main fail will get less lines, and all we will save our eyes and minds reading shortly lines jajaj

That's apply for html code too..,

**Comment by gmorales254** [comment]
@Max-Oliver Im checking out that in this ticket  #5 
Best regards and thanks about the sugesstion
