### ISSUE TITLE
Agregar reportes por cada canal que se maneje.

### ISSUE THREAD

**Issue by gmorales254** [gmorales254/CRMLite#8]
El reporte que se tiene actualmente solo maneja telefonía ya que uContact no permite agregar todas las campañas sino, de manera separada.

- [x]  Reporte de telefonia
- [x]  Reporte de SMS - Wpp
- [x]  Reporte de Facebook
- [x]  Reporte de email

**Comment by Max-Oliver** [comment]
Probablemente esto sea enhancement no bugs

**Comment by gmorales254** [comment]
@Max-Oliver Lo tomé como bug porque era un problema para la producción no tener todos los datos, pero lo mando como enhancement, Tenes razón. 

Saludos

**Comment by Max-Oliver** [comment]
Claro pero no deja de ser un featuring, que se nesecita para producción
